<a href="https://colab.research.google.com/github/Z0s-and-O1s/TNSIF_Training/blob/main/RT_Data_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('Presentation-TASK - Sheet1.csv')
data.head()

,UID,Participant Name,Group No,Project Name,Technical knowledge(10),Communication(10),Attrire(5),Marks
0,T160600201,Gayathri Munasu,3.0,"types of Data visuals,application",6.0,6.0,3.0,NaN
1,T160600202,Namratha Bajjuri,4.0,Comparision of t-SNE,6.0,6.0,4.0,NaN
2,T160600203,Nikitha Sambangi,NaN,NaN,NaN,NaN,NaN,NaN
3,T160600204,Akhil Reddy Komireddy,3.0,KNN,6.0,7.0,3.0,NaN
4,T160600205,CHARAN KONDA,3.0,"Applications of SVM ,",6.0,7.0,3.0,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UID                      66 non-null     object
 1   Participant Name         66 non-null     object
 2   Group No                 59 non-null     float64
 3   Project Name             36 non-null     object
 4   Technical knowledge(10)  56 non-null     float64
 5   Communication(10)        56 non-null     float64
 6   Attrire(5)               54 non-null     float64
 7   Marks                    0 non-null      float64
dtypes: float64(5), object(3)
memory usage: 4.3+ KB

In [ ]:
data.describe()

,Group No,Technical knowledge(10),Communication(10),Attrire(5),Marks
count,59.000000,56.000000,56.000000,54.000000,0.0
mean,4.101695,5.982143,6.035714,3.740741,NaN
std,1.854119,0.999838,0.893701,0.520710,NaN
min,1.000000,3.000000,3.000000,3.000000,NaN
25%,2.500000,5.000000,6.000000,3.000000,NaN
50%,4.000000,6.000000,6.000000,4.000000,NaN
75%,6.000000,7.000000,7.000000,4.000000,NaN
max,6.000000,8.000000,7.000000,5.000000,NaN

In [ ]:
data.isnull()

,UID,Participant Name,Group No,Project Name,Technical knowledge(10),Communication(10),Attrire(5),Marks
0,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,True
2,False,False,True,True,True,True,True,True
3,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...
61,False,False,False,True,False,False,False,True
62,False,False,False,False,False,False,False,True
63,False,False,False,True,False,False,False,True
64,False,False,False,False,False,False,False,True
65,False,False,False,False,False,False,False,True

In [ ]:
data.isnull().sum()

UID                         0
Participant Name            0
Group No                    7
Project Name               30
Technical knowledge(10)    10
Communication(10)          10
Attrire(5)                 12
Marks                      66
dtype: int64

In [ ]:
data = data.drop(columns='Marks')
data

,UID,Participant Name,Group No,Project Name,Technical knowledge(10),Communication(10),Attrire(5)
0,T160600201,Gayathri Munasu,3.0,"types of Data visuals,application",6.0,6.0,3.0
1,T160600202,Namratha Bajjuri,4.0,Comparision of t-SNE,6.0,6.0,4.0
2,T160600203,Nikitha Sambangi,NaN,NaN,NaN,NaN,NaN
3,T160600204,Akhil Reddy Komireddy,3.0,KNN,6.0,7.0,3.0
4,T160600205,CHARAN KONDA,3.0,"Applications of SVM ,",6.0,7.0,3.0
...,...,...,...,...,...,...,...
61,T160600262,Sruthi Shabothu,6.0,NaN,6.0,6.0,4.0
62,T160600263,Bachu Nagasri,1.0,Missing values & Duplicates,7.0,7.0,4.0
63,T160600264,Nandini Dhondi,6.0,NaN,5.0,6.0,4.0
64,T160600265,Gajula Sathvika,3.0,Coding,8.0,7.0,4.0
65,T160600266,Akshitha maddela,4.0,Conclusion,5.0,6.0,4.0

In [ ]:
data = data.dropna()
data

,UID,Participant Name,Group No,Project Name,Technical knowledge(10),Communication(10),Attrire(5)
0,T160600201,Gayathri Munasu,3.0,"types of Data visuals,application",6.0,6.0,3.0
1,T160600202,Namratha Bajjuri,4.0,Comparision of t-SNE,6.0,6.0,4.0
3,T160600204,Akhil Reddy Komireddy,3.0,KNN,6.0,7.0,3.0
4,T160600205,CHARAN KONDA,3.0,"Applications of SVM ,",6.0,7.0,3.0
5,T160600206,Md Faisal,4.0,Functions,6.0,6.0,4.0
6,T160600207,BOPPANI BHARGAVI,2.0,Feature Engineering (numeric),8.0,7.0,4.0
9,T160600210,Goutham Putta,4.0,Applications of t-SNE,6.0,6.0,3.0
10,T160600211,Dakkata Madhu,3.0,"Intro of AI,ML and SVM",4.0,3.0,3.0
12,T160600213,Akshitha Samudrala,1.0,Advantages & Applications,3.0,4.0,4.0
13,T160600214,Gayathri Bommagani,3.0,SVM vs KNN,5.0,5.0,4.0
15,T160600216,Sri Lahari Buddarthi,4.0,Visualization,5.0,5.0,4.0
17,T160600218,PEETHALA JYOTHI SWAROOP BABU,5.0,coding,6.0,7.0,4.0
18,T160600219,Rathakanti Rohith,1.0,Conclusion,7.0,6.0,4.0
20,T160600221,Sathvika P,5.0,Real time examples,6.0,5.0,4.0
21,T160600222,Madipadiga Kousheel,2.0,Feature creation,7.0,7.0,4.0
22,T160600223,Kanigiri Devika,3.0,Demonstration of SVM & KNN,7.0,7.0,4.0
28,T160600229,Mohammed Masoom Baba,2.0,Categorical data,7.0,6.0,5.0
30,T160600231,Sowjanya Sirigadde,2.0,Date & time Features,6.0,5.0,4.0
32,T160600233,Murali Krishna Kalakala,2.0,Feature Eng and selection,7.0,6.0,3.0
33,T160600234,Nikshitha Lingamalla,3.0,Applications of KNN,6.0,7.0,4.0
35,T160600236,Vaishnavi Erla,5.0,Conclusion,6.0,6.0,5.0
36,T160600237,Maheshwari Gunreddy,2.0,Handling Missing values,7.0,6.0,4.0
37,T160600238,Sravani jadi,4.0,Advantages & Disadvantages of SNE,5.0,5.0,3.0
38,T160600239,Minnu Sri Jakku,5.0,Advantages of DV,6.0,6.0,4.0
39,T160600240,Lodugu Ravi Kumar,1.0,Feature Scaling,4.0,3.0,4.0
43,T160600244,Bharath Kumar Moyyadi,5.0,"Matplotlib ,seaborn,plotly",7.0,7.0,4.0
44,T160600245,SRI SAI MADHURVIND MUDUTHANAPELLY,1.0,Outliers,8.0,7.0,3.0
45,T160600246,Chaitanya Mullye,4.0,t-SNE,7.0,6.0,4.0
47,T160600248,Kavya Pitla,2.0,Feature Selection,7.0,7.0,4.0
52,T160600253,Srikrishna Thaniya Vemula,4.0,Purpose of SNE,5.0,6.0,3.0
54,T160600255,Uppu Pushpa,1.0,Encoding,6.0,6.0,4.0
55,T160600256,Varshini Reddy Anantha,2.0,Outliers,6.0,6.0,4.0
59,T160600260,Vunguturi Naga Venkata Sai Adithya,1.0,Data preprocessing,7.0,7.0,4.0
62,T160600263,Bachu Nagasri,1.0,Missing values & Duplicates,7.0,7.0,4.0
64,T160600265,Gajula Sathvika,3.0,Coding,8.0,7.0,4.0
65,T160600266,Akshitha maddela,4.0,Conclusion,5.0,6.0,4.0

In [ ]:
data.isnull().sum()

UID                        0
Participant Name           0
Group No                   0
Project Name               0
Technical knowledge(10)    0
Communication(10)          0
Attrire(5)                 0
dtype: int64

In [ ]:
data['Total_Marks(25)'] = (data['Technical knowledge(10)']+data['Communication(10)']+data['Attrire(5)'])
data

/tmp/ipykernel_970/3825471557.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Total_Marks(25)'] = (data['Technical knowledge(10)']+data['Communication(10)']+data['Attrire(5)'])

,UID,Participant Name,Group No,Project Name,Technical knowledge(10),Communication(10),Attrire(5),Total_Marks(25)
0,T160600201,Gayathri Munasu,3.0,"types of Data visuals,application",6.0,6.0,3.0,15.0
1,T160600202,Namratha Bajjuri,4.0,Comparision of t-SNE,6.0,6.0,4.0,16.0
3,T160600204,Akhil Reddy Komireddy,3.0,KNN,6.0,7.0,3.0,16.0
4,T160600205,CHARAN KONDA,3.0,"Applications of SVM ,",6.0,7.0,3.0,16.0
5,T160600206,Md Faisal,4.0,Functions,6.0,6.0,4.0,16.0
6,T160600207,BOPPANI BHARGAVI,2.0,Feature Engineering (numeric),8.0,7.0,4.0,19.0
9,T160600210,Goutham Putta,4.0,Applications of t-SNE,6.0,6.0,3.0,15.0
10,T160600211,Dakkata Madhu,3.0,"Intro of AI,ML and SVM",4.0,3.0,3.0,10.0
12,T160600213,Akshitha Samudrala,1.0,Advantages & Applications,3.0,4.0,4.0,11.0
13,T160600214,Gayathri Bommagani,3.0,SVM vs KNN,5.0,5.0,4.0,14.0
15,T160600216,Sri Lahari Buddarthi,4.0,Visualization,5.0,5.0,4.0,14.0
17,T160600218,PEETHALA JYOTHI SWAROOP BABU,5.0,coding,6.0,7.0,4.0,17.0
18,T160600219,Rathakanti Rohith,1.0,Conclusion,7.0,6.0,4.0,17.0
20,T160600221,Sathvika P,5.0,Real time examples,6.0,5.0,4.0,15.0
21,T160600222,Madipadiga Kousheel,2.0,Feature creation,7.0,7.0,4.0,18.0
22,T160600223,Kanigiri Devika,3.0,Demonstration of SVM & KNN,7.0,7.0,4.0,18.0
28,T160600229,Mohammed Masoom Baba,2.0,Categorical data,7.0,6.0,5.0,18.0
30,T160600231,Sowjanya Sirigadde,2.0,Date & time Features,6.0,5.0,4.0,15.0
32,T160600233,Murali Krishna Kalakala,2.0,Feature Eng and selection,7.0,6.0,3.0,16.0
33,T160600234,Nikshitha Lingamalla,3.0,Applications of KNN,6.0,7.0,4.0,17.0
35,T160600236,Vaishnavi Erla,5.0,Conclusion,6.0,6.0,5.0,17.0
36,T160600237,Maheshwari Gunreddy,2.0,Handling Missing values,7.0,6.0,4.0,17.0
37,T160600238,Sravani jadi,4.0,Advantages & Disadvantages of SNE,5.0,5.0,3.0,13.0
38,T160600239,Minnu Sri Jakku,5.0,Advantages of DV,6.0,6.0,4.0,16.0
39,T160600240,Lodugu Ravi Kumar,1.0,Feature Scaling,4.0,3.0,4.0,11.0
43,T160600244,Bharath Kumar Moyyadi,5.0,"Matplotlib ,seaborn,plotly",7.0,7.0,4.0,18.0
44,T160600245,SRI SAI MADHURVIND MUDUTHANAPELLY,1.0,Outliers,8.0,7.0,3.0,18.0
45,T160600246,Chaitanya Mullye,4.0,t-SNE,7.0,6.0,4.0,17.0
47,T160600248,Kavya Pitla,2.0,Feature Selection,7.0,7.0,4.0,18.0
52,T160600253,Srikrishna Thaniya Vemula,4.0,Purpose of SNE,5.0,6.0,3.0,14.0
54,T160600255,Uppu Pushpa,1.0,Encoding,6.0,6.0,4.0,16.0
55,T160600256,Varshini Reddy Anantha,2.0,Outliers,6.0,6.0,4.0,16.0
59,T160600260,Vunguturi Naga Venkata Sai Adithya,1.0,Data preprocessing,7.0,7.0,4.0,18.0
62,T160600263,Bachu Nagasri,1.0,Missing values & Duplicates,7.0,7.0,4.0,18.0
64,T160600265,Gajula Sathvika,3.0,Coding,8.0,7.0,4.0,19.0
65,T160600266,Akshitha maddela,4.0,Conclusion,5.0,6.0,4.0,15.0

In [ ]:
data.to_csv('processed_data.csv', index=False)

In [ ]:
import plotly.express as px

In [ ]:
# 1. Top 5 students based on Total Score (Technical + Communication + Attire)

Sorted_marks = data.sort_values(by='Total_Marks(25)', ascending=False).head(5)
display(Sorted_marks)

fig = px.bar(
    Sorted_marks,
    x='Participant Name',
    y='Total_Marks(25)',
    title='Top 5 Students Based on Total Marks',
    color='Total_Marks(25)',
    text='Total_Marks(25)'
)

fig.update_layout(
    xaxis_title="Student Name",
    yaxis_title="Total Marks"
)

fig.show()

,UID,Participant Name,Group No,Project Name,Technical knowledge(10),Communication(10),Attrire(5),Total_Marks(25)
64,T160600265,Gajula Sathvika,3.0,Coding,8.0,7.0,4.0,19.0
6,T160600207,BOPPANI BHARGAVI,2.0,Feature Engineering (numeric),8.0,7.0,4.0,19.0
28,T160600229,Mohammed Masoom Baba,2.0,Categorical data,7.0,6.0,5.0,18.0
21,T160600222,Madipadiga Kousheel,2.0,Feature creation,7.0,7.0,4.0,18.0
59,T160600260,Vunguturi Naga Venkata Sai Adithya,1.0,Data preprocessing,7.0,7.0,4.0,18.0

In [ ]:
# 2. Top 5 students in Technical

Sorted_Tech = data.sort_values(by='Technical knowledge(10)', ascending=False).head(5)
display(Sorted_Tech)

fig = px.bar(
    Sorted_Tech,
    x='Participant Name',
    y='Technical knowledge(10)',
    color='Technical knowledge(10)',
    text='Technical knowledge(10)',
    title='Top 5 Students in Technical'
)

fig.update_traces(textposition='outside')

fig.update_layout(
    xaxis_title='Student Name',
    yaxis_title='Technical Marks'
)

fig.show()

,UID,Participant Name,Group No,Project Name,Technical knowledge(10),Communication(10),Attrire(5),Total_Marks(25)
44,T160600245,SRI SAI MADHURVIND MUDUTHANAPELLY,1.0,Outliers,8.0,7.0,3.0,18.0
64,T160600265,Gajula Sathvika,3.0,Coding,8.0,7.0,4.0,19.0
6,T160600207,BOPPANI BHARGAVI,2.0,Feature Engineering (numeric),8.0,7.0,4.0,19.0
22,T160600223,Kanigiri Devika,3.0,Demonstration of SVM & KNN,7.0,7.0,4.0,18.0
45,T160600246,Chaitanya Mullye,4.0,t-SNE,7.0,6.0,4.0,17.0

In [ ]:
# 3. Top 5 students in Communication

Sorted_Comm = data.sort_values(by='Communication(10)', ascending=False).head(5)
display(Sorted_Comm)

fig = px.bar(
    Sorted_Comm,
    x='Participant Name',
    y='Communication(10)',
    color='Communication(10)',
    text='Communication(10)',
    title='Top 5 Students in Communication'
)

fig.update_traces(textposition='outside')

fig.update_layout(
    xaxis_title='Student Name',
    yaxis_title='Communication Marks'
)

fig.show()

,UID,Participant Name,Group No,Project Name,Technical knowledge(10),Communication(10),Attrire(5),Total_Marks(25)
4,T160600205,CHARAN KONDA,3.0,"Applications of SVM ,",6.0,7.0,3.0,16.0
3,T160600204,Akhil Reddy Komireddy,3.0,KNN,6.0,7.0,3.0,16.0
17,T160600218,PEETHALA JYOTHI SWAROOP BABU,5.0,coding,6.0,7.0,4.0,17.0
6,T160600207,BOPPANI BHARGAVI,2.0,Feature Engineering (numeric),8.0,7.0,4.0,19.0
47,T160600248,Kavya Pitla,2.0,Feature Selection,7.0,7.0,4.0,18.0

In [ ]:
# 4. Top 5 students in Attire

Sorted_Att = data.sort_values(by='Attrire(5)', ascending=False).head(5)
display(Sorted_Att)

fig = px.bar(
    Sorted_Att,
    x='Participant Name',
    y='Attrire(5)',
    color='Attrire(5)',
    text='Attrire(5)',
    title='Top 5 Students in Attire'
)

fig.update_traces(textposition='outside')

fig.update_layout(
    xaxis_title='Student Name',
    yaxis_title='Attire Marks'
)

fig.show()

,UID,Participant Name,Group No,Project Name,Technical knowledge(10),Communication(10),Attrire(5),Total_Marks(25)
35,T160600236,Vaishnavi Erla,5.0,Conclusion,6.0,6.0,5.0,17.0
28,T160600229,Mohammed Masoom Baba,2.0,Categorical data,7.0,6.0,5.0,18.0
1,T160600202,Namratha Bajjuri,4.0,Comparision of t-SNE,6.0,6.0,4.0,16.0
13,T160600214,Gayathri Bommagani,3.0,SVM vs KNN,5.0,5.0,4.0,14.0
64,T160600265,Gajula Sathvika,3.0,Coding,8.0,7.0,4.0,19.0

In [ ]:
fig = px.box(
    data,
    y=[
        'Technical knowledge(10)',
        'Communication(10)',
        'Attrire(5)'
    ],
    title='Marks Distribution'
)

fig.update_layout(
    template='plotly_white'
)

fig.show()

In [ ]:
print("="*60)
print("DASHBOARD SUMMARY")
print("="*60)

# Highest Total Marks
highest_total = data['Total_Marks(25)'].max()
top_total = data[data['Total_Marks(25)'] == highest_total]

print(f"\nHighest Total Marks obtained        : {highest_total}")
print("Topper(s):")
for name in top_total['Participant Name']:
    print(f"   • {name}")

# Highest Technical Marks
highest_tech = data['Technical knowledge(10)'].max()
top_tech = data[data['Technical knowledge(10)'] == highest_tech]

print(f"\nHighest Technical Marks obtained    : {highest_tech}")
print("Topper(s):")
for name in top_tech['Participant Name']:
    print(f"   • {name}")

# Highest Communication Marks
highest_comm = data['Communication(10)'].max()
top_comm = data[data['Communication(10)'] == highest_comm]

print(f"\nHighest Communication Marks obtained: {highest_comm}")
print("Topper(s):")
for name in top_comm['Participant Name']:
    print(f"   • {name}")

# Highest Attire Marks
highest_att = data['Attrire(5)'].max()
top_att = data[data['Attrire(5)'] == highest_att]

print(f"\nHighest Attire Marks obtained       : {highest_att}")
print("Topper(s):")
for name in top_att['Participant Name']:
    print(f"   • {name}")

============================================================
DASHBOARD SUMMARY
============================================================

Highest Total Marks obtained        : 19.0
Topper(s):
   • BOPPANI BHARGAVI
   • Gajula Sathvika

Highest Technical Marks obtained    : 8.0
Topper(s):
   • BOPPANI BHARGAVI
   • SRI SAI MADHURVIND MUDUTHANAPELLY
   • Gajula Sathvika

Highest Communication Marks obtained: 7.0
Topper(s):
   • Akhil Reddy Komireddy
   • CHARAN KONDA
   • BOPPANI BHARGAVI
   • PEETHALA JYOTHI SWAROOP BABU
   • Madipadiga Kousheel
   • Kanigiri Devika
   • Nikshitha Lingamalla
   • Bharath Kumar Moyyadi
   • SRI SAI MADHURVIND MUDUTHANAPELLY
   • Kavya Pitla
   • Vunguturi Naga Venkata Sai Adithya
   • Bachu Nagasri
   • Gajula Sathvika

Highest Attire Marks obtained       : 5.0
Topper(s):
   • Mohammed Masoom Baba
   • Vaishnavi Erla