<a href="https://colab.research.google.com/github/Z0s-and-O1s/TNSIF_Training/blob/main/TNS_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#create series
s = pd.Series([1,2,3,4,5,6,7])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

# Descriptive Statistics

**s.describe():** Provides a quick summary of the data.

This method gives a statistical summary of the Series, including count, mean, standard deviation, minimum, maximum, and quartile values.

In [ ]:
# Descriptive statistics
print(s.describe())

count    7.000000
mean     4.000000
std      2.160247
min      1.000000
25%      2.500000
50%      4.000000
75%      5.500000
max      7.000000
dtype: float64

 **s.mean():** Computes the mean of the data.

 **s.std():** Computes the standard deviation.

 **s.min() and s.max():** Computes the minimum and maximum values.

In [ ]:
print(s.mean())
print(s.std())
print(s.min())
print(s.max())

4.0
2.160246899469287
1
7

#Data Manipulation

**s.map(func):** Applies a function to each element in the Series.

In [ ]:
mapping = s.map(lambda x :x*2)
print(mapping)
print(s)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

**s.apply(func):** Similar to map, but more flexible. (Can be used Data Frames as well, where as map is only for Series)

In [ ]:
applies = s.apply(lambda x : x ** 2)
print(applies)
print(s)

0     1
1     4
2     9
3    16
4    25
5    36
6    49
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

**s.sort_values():** Sorts the Series.

In [ ]:
s1 = pd.Series([4,7,54,23,92,41])
sorted = s1.sort_values()
print(sorted)

0     4
1     7
3    23
5    41
2    54
4    92
dtype: int64

**s.drop(index):** Drops specified labels from the Series.(not deletes)

In [ ]:
dropped = s.drop(1)
print(dropped)
print(s)

0    1
2    3
3    4
4    5
5    6
6    7
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

#Handling Missing Data

**s.isnull():** Checks for missing values, returns a Series of booleans.

In [ ]:
s2 = pd.Series([2,4,6,np.nan,7,0])
print(s2.isnull())

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

**s.notnull():** Opposite of isnull().

In [ ]:
print(s2.notnull())

0     True
1     True
2     True
3    False
4     True
5     True
dtype: bool

**s.fillna(value):** Fills missing values with a specified value.

In [ ]:
print(s2.fillna(0))

0    2.0
1    4.0
2    6.0
3    0.0
4    7.0
5    0.0
dtype: float64

**s.dropna():** Drops all rows that contain missing values.like None

In [ ]:
s3 = pd.Series([4,7,3,None,8,2,np.nan])
print(s3)
print(s3.dropna())

0    4.0
1    7.0
2    3.0
3    NaN
4    8.0
5    2.0
6    NaN
dtype: float64
0    4.0
1    7.0
2    3.0
4    8.0
5    2.0
dtype: float64

# Indexing, Slicing, and Filtering
**s.iloc[ ]:** Purely integer-location based indexing.
(+)-left to right,(-)-right to left

In [ ]:
print(s.iloc[2])  #1,2,3,4,5,6,7
print(s.iloc[-2])  #6

3
6

**s.loc[ ]:** Label-based indexing.(only we can give positive values not negitive)

In [ ]:
print(s.loc[2])
print(s.loc[1:2])

3
1    2
2    3
dtype: int64

**s[s > n]:** Filters and returns elements greater than n.

In [ ]:
greater_num = s[s<=5]
print(greater_num)

0    1
1    2
2    3
3    4
4    5
dtype: int64

#Aggregation

##s.sum(): Sums up the values

In [ ]:
print(s.sum())

28

##s.cumsum() : cumulative Sum

In [ ]:
print(s.cumsum())

0     1
1     3
2     6
3    10
4    15
5    21
6    28
dtype: int64

**s.aggregate(func):** Aggregates using one or more operations. like
s.aggregate(['sum','mean','std'])

In [ ]:
print(s.aggregate(['sum','std','mean']))

sum     28.000000
std      2.160247
mean     4.000000
dtype: float64

#creating DataFrames

In [ ]:
data = {
    "name" : ['sruthi','hema','ashok','rohith','venkatesh','mohith','Azmath',
              'Ravi','priya','Nikhitha','shila','bhoomika','sushma'],
    "age" : [23,32,21,15,65,51,22,43,25,89,99,20,19],
    "branch" : ['CSE','ECE','AIML','CSM','DS','IOT','CS','Mech','Civil','EEE','IT',
                'AIDS','FD'],
    "Address" : ['Hyd','panjab','Assam','Bihar','JK','chennai','Bglr','kerala','pune',
                 'Mumbai','Goa','Pondi','Coimb']
}
df = pd.DataFrame(data)
df

         name  age branch  Address
0      sruthi   23    CSE      Hyd
1        hema   32    ECE   panjab
2       ashok   21   AIML    Assam
3      rohith   15    CSM    Bihar
4   venkatesh   65     DS       JK
5      mohith   51    IOT  chennai
6      Azmath   22     CS     Bglr
7        Ravi   43   Mech   kerala
8       priya   25  Civil     pune
9    Nikhitha   89    EEE   Mumbai
10      shila   99     IT      Goa
11   bhoomika   20   AIDS    Pondi
12     sushma   19     FD    Coimb

df.head()

In [ ]:
df.head(7)

        name  age branch  Address
0     sruthi   23    CSE      Hyd
1       hema   32    ECE   panjab
2      ashok   21   AIML    Assam
3     rohith   15    CSM    Bihar
4  venkatesh   65     DS       JK
5     mohith   51    IOT  chennai
6     Azmath   22     CS     Bglr

df.tail()

In [ ]:
df.tail(7)

        name  age branch Address
6     Azmath   22     CS    Bglr
7       Ravi   43   Mech  kerala
8      priya   25  Civil    pune
9   Nikhitha   89    EEE  Mumbai
10     shila   99     IT     Goa
11  bhoomika   20   AIDS   Pondi
12    sushma   19     FD   Coimb

merged_df = pd.merge(df1, df2, on='Name')

In [ ]:
data1 = {"name" : ['sruthi','hema','ashok','rohith','venkatesh','mohith','Azmath',
              'Ravi','priya','Nikhitha','shila','bhoomika','sushma'],
    "age" : [23,32,21,15,65,51,22,43,25,89,99,20,19]}
df1 = pd.DataFrame(data1)

data2 = {
    "name" : ['sruthi','hema','ashok','rohith','venkatesh','mohith','Azmath',
              'Ravi','priya','Nikhitha','shila','bhoomika','sushma'],
    "branch" : ['CSE','ECE','AIML','CSM','DS','IOT','CS','Mech','Civil','EEE','IT',
                'AIDS','FD']
}
df2 = pd.DataFrame(data2)
merged = pd.merge(df1,df2,on="name")
merged

         name  age branch
0      sruthi   23    CSE
1        hema   32    ECE
2       ashok   21   AIML
3      rohith   15    CSM
4   venkatesh   65     DS
5      mohith   51    IOT
6      Azmath   22     CS
7        Ravi   43   Mech
8       priya   25  Civil
9    Nikhitha   89    EEE
10      shila   99     IT
11   bhoomika   20   AIDS
12     sushma   19     FD

In [ ]:
print(df.describe())

             age
count  13.000000
mean   40.307692
std    27.935594
min    15.000000
25%    21.000000
50%    25.000000
75%    51.000000
max    99.000000

##Importing Dataset
- Importing datasets into Pandas is straightforward, and Pandas supports various file formats like csv, xlsx, json, sql etc.
- df = pd.read_csv('')

df.shape: The df.shape attribute of a DataFrame returns a tuple representing the dimensionality of the DataFrame. The first element of the tuple is the number of rows, and the second is the number of columns. This is useful when you need to know how large the dataset is, such as when you are preprocessing data or ensuring that data manipulations have executed correctly.

df.columns  # Lists all the column names in the DataFrame

Display the data types of each column

Display summary statistics for numerical columns

In [ ]:
# Step 1: Import required libraries
import pandas as pd
import numpy as np
# Step 2: Upload CSV file from your system
from google.colab import files
uploaded = files.upload()

# Step 3: Read the uploaded CSV file
# Replace 'your_file.csv' with actual uploaded file name
df = pd.read_csv(list(uploaded.keys())[0])

# Display first 5 rows
print("First 5 rows:")
print(df.head())

# Step 4: Basic Information
print("\nDataset Info:")
print(df.info())

print("\nSummary Statistics:")
print(df.describe())

# Step 5: Handling Missing Values
print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing values with 0 (example)
df = df.fillna(0)

# Step 6: Filtering Data (example)
# Filter days with high temperature (>30)
if 'temperature' in df.columns:
    filtered_df = df[df['temperature'] > 10]
    print("\nFiltered Data (Temperature > 30):")
    print(filtered_df)

# Step 7: Adding New Column
# Example: classify weather based on temperature
if 'temperature' in df.columns:
    df['weather_type'] = df['temperature'].apply(
        lambda x: 'Hot' if x >= 30 else 'Normal'
    )

# Step 8: GroupBy Example
# Average temperature based on weather condition
if 'weather_condition' in df.columns:
    group_data = df.groupby('weather_condition')['temperature'].mean()
    print("\nAverage Temperature by Weather Condition:")
    print(group_data)

# Step 9: Save Modified File
df.to_csv("processed_data.csv", index=False)

# Step 10: Download the processed file
from google.colab import files
files.download("processed_data.csv")

Saving cleaned_rainfall.csv to cleaned_rainfall (1).csv
First 5 rows:
         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2022-01-01      12.5         15.2      78.0         8.5             rainy
1  2022-01-02       8.2         17.8      65.0         5.2             rainy
2  2022-01-03       0.0         20.1      52.0         3.1             sunny
3  2022-01-04       3.7         18.6      71.0         6.7             rainy
4  2022-01-05      21.1         14.8      82.0         9.3             rainy

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               53 non-null     object
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB
None

Summary Statistics:
        rainfall  temperature   humidity  wind_speed
count  53.000000    53.000000  53.000000   53.000000
mean    9.049057    17.950943  69.245283    6.403774
std     6.712521     2.500663  11.969361    2.209069
min     0.000000    13.900000  44.000000    2.100000
25%     3.900000    16.100000  62.000000    4.700000
50%     8.300000    17.800000  72.000000    6.700000
75%    14.800000    19.400000  78.000000    8.300000
max    21.800000    23.400000  89.000000   10.500000

Missing Values:
date                 1
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

Filtered Data (Temperature > 30):
Empty DataFrame
Columns: [date, rainfall, temperature, humidity, wind_speed, weather_condition]
Index: []

Average Temperature by Weather Condition:
weather_condition
0         0.000000
rainy    16.966667
sunny    21.709091
Name: temperature, dtype: float64